"""Configuration module"""
from .settings import *

__all__ = [
    'BASE_DIR', 'DATA_DIR', 'BATCH_DATA_PATH', 'API_DATA_PATH',
    'OUTPUT_DIR', 'METRICS_DIR', 'REPORTS_DIR', 'PROCESSED_DIR',
    'CHUNK_SIZE', 'EC2_CHUNK_SIZE', 'MAX_FILE_SIZE_MB',
    'TAUX_OCCUPATION_SEUIL_CONGESTION', 'CAPTEUR_DEFAILLANT_HEURES',
    'VITESSE_REFERENCE_NORMALE', 'ARRONDISSEMENTS_PARIS',
    'IMPACT_CHANTIERS', 'SEVERITE_RATP', 'CONDITIONS_METEO',
    'DYNAMODB_TABLES'
]

